"""Custom widget persistence for HAL's creative playground.

Widgets are self-contained HTML documents (inline CSS + JS) generated by
the LLM and stored in data/widgets.json.  The frontend renders each one
in a sandboxed iframe so arbitrary JS can run without touching the parent."""
from __future__ import annotations

import json
import time
import uuid
from pathlib import Path

_STORE = Path(__file__).parent.parent.parent / "data" / "widgets.json"


def _load() -> list[dict]:
    if _STORE.exists():
        try:
            return json.loads(_STORE.read_text())
        except Exception:
            return []
    return []


def _save(widgets: list[dict]) -> None:
    _STORE.parent.mkdir(parents=True, exist_ok=True)
    _STORE.write_text(json.dumps(widgets, ensure_ascii=False, indent=2))


def save_widget(name: str, description: str, html_content: str) -> dict:
    """Persist a new widget and return its record."""
    widgets = _load()
    record = {
        "id": str(uuid.uuid4())[:8],
        "name": name,
        "description": description,
        "html_content": html_content,
        "created_at": int(time.time()),
    }
    widgets.append(record)
    _save(widgets)
    return record


def list_widgets() -> list[dict]:
    """Return all saved widgets (without html_content to keep payload small)."""
    return [
        {k: v for k, v in w.items() if k != "html_content"}
        for w in _load()
    ]


def get_widget(widget_id: str) -> dict | None:
    for w in _load():
        if w["id"] == widget_id:
            return w
    return None


def delete_widget(widget_id: str) -> bool:
    widgets = _load()
    new = [w for w in widgets if w["id"] != widget_id]
    if len(new) == len(widgets):
        return False
    _save(new)
    return True
